from django.urls import path

from .views import (
    acciones_personal,
    acciones_personal_cancelar,
    acciones_personal_detalle,
    acciones_personal_guardar,
    acciones_personal_listar,
    buscar,
    control_nomina,
    control_nomina_adelanto,
    control_nomina_adelantos_listar,
    control_nomina_anular,
    control_nomina_aprobar,
    control_nomina_crear_periodo,
    control_nomina_detalle_periodo,
    control_nomina_generar,
    control_nomina_guardar_entrada,
    control_nomina_periodos,
    control_vacaciones,
    control_vacaciones_calendario,
    control_vacaciones_descontar,
    control_vacaciones_descuentos,
    control_vacaciones_eliminar_plan,
    control_vacaciones_listar,
    control_vacaciones_planificar,
    detalle,
    guardar,
    index,
    maestro,
)

app_name = "empleados"

urlpatterns = [
    path("", index, name="index"),
    path("maestro/", maestro, name="maestro"),
    path("acciones-personal/", acciones_personal, name="acciones_personal"),
    path("acciones-personal/listar/", acciones_personal_listar, name="acciones_personal_listar"),
    path("acciones-personal/detalle/<int:accion_id>/", acciones_personal_detalle, name="acciones_personal_detalle"),
    path("acciones-personal/guardar/", acciones_personal_guardar, name="acciones_personal_guardar"),
    path("acciones-personal/cancelar/", acciones_personal_cancelar, name="acciones_personal_cancelar"),
    path("control-vacaciones/", control_vacaciones, name="control_vacaciones"),
    path("control-vacaciones/listar/", control_vacaciones_listar, name="control_vacaciones_listar"),
    path("control-vacaciones/calendario/", control_vacaciones_calendario, name="control_vacaciones_calendario"),
    path("control-vacaciones/descontar/", control_vacaciones_descontar, name="control_vacaciones_descontar"),
    path("control-vacaciones/descuentos/", control_vacaciones_descuentos, name="control_vacaciones_descuentos"),
    path("control-vacaciones/planificar/", control_vacaciones_planificar, name="control_vacaciones_planificar"),
    path("control-vacaciones/eliminar-plan/", control_vacaciones_eliminar_plan, name="control_vacaciones_eliminar_plan"),
    path("control-nomina/", control_nomina, name="control_nomina"),
    path("control-nomina/periodos/", control_nomina_periodos, name="control_nomina_periodos"),
    path("control-nomina/crear-periodo/", control_nomina_crear_periodo, name="control_nomina_crear_periodo"),
    path("control-nomina/detalle-periodo/<int:periodo_id>/", control_nomina_detalle_periodo, name="control_nomina_detalle_periodo"),
    path("control-nomina/generar/", control_nomina_generar, name="control_nomina_generar"),
    path("control-nomina/guardar-entrada/", control_nomina_guardar_entrada, name="control_nomina_guardar_entrada"),
    path("control-nomina/aprobar/", control_nomina_aprobar, name="control_nomina_aprobar"),
    path("control-nomina/anular/", control_nomina_anular, name="control_nomina_anular"),
    path("control-nomina/adelanto/", control_nomina_adelanto, name="control_nomina_adelanto"),
    path("control-nomina/adelantos-listar/", control_nomina_adelantos_listar, name="control_nomina_adelantos_listar"),
    path("buscar/", buscar, name="buscar"),
    path("detalle/<int:empleado_id>/", detalle, name="detalle"),
    path("guardar/", guardar, name="guardar"),
]
