# Generated by Django 5.2.12 on 2026-03-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartaPlantilla',
            fields=[
                ('id_plantilla', models.AutoField(db_column='ID_PLANTILLA', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100, unique=True)),
                ('asunto', models.CharField(db_column='ASUNTO', max_length=255)),
                ('cuerpo', models.TextField(db_column='CUERPO')),
                ('activa', models.BooleanField(db_column='ACTIVA', default=True)),
                ('creado_por_id', models.BigIntegerField(db_column='CREADO_POR_ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_CREACION')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='FECHA_MODIFICACION')),
            ],
            options={
                'db_table': 'CARTA_PLANTILLA',
            },
        ),
    ]
