# Generated by Django 5.2.12 on 2026-06-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefacturas_app', '0009_cab_recibo_modificacion_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVariable',
            fields=[
                ('id_config', models.AutoField(db_column='ID_CONFIG', primary_key=True, serialize=False)),
                ('prefijo', models.CharField(db_column='PREFIJO', max_length=10, unique=True)),
                ('pos_producto', models.IntegerField(db_column='POS_PRODUCTO', default=2)),
                ('len_producto', models.IntegerField(db_column='LEN_PRODUCTO', default=5)),
                ('pos_valor', models.IntegerField(db_column='POS_VALOR', default=7)),
                ('len_valor', models.IntegerField(db_column='LEN_VALOR', default=5)),
                ('divisor_valor', models.DecimalField(db_column='DIVISOR_VALOR', decimal_places=4, default=1000, max_digits=10)),
                ('tipo', models.CharField(db_column='TIPO', default='peso', max_length=20)),
                ('activo', models.CharField(db_column='ACTIVO', default='Y', max_length=1)),
            ],
            options={
                'db_table': 'CODIGO_VARIABLE',
            },
        ),
    ]
