# Generated by Django 5.2.12 on 2026-06-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefacturas_app', '0010_codigovariable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloConversion',
            fields=[
                ('id_articulo', models.CharField(db_column='ID_ARTICULO', max_length=20, primary_key=True, serialize=False)),
                ('id_articulo_base', models.CharField(db_column='ID_ARTICULO_BASE', max_length=20)),
                ('factor', models.DecimalField(db_column='FACTOR', decimal_places=4, default=1.0, max_digits=19)),
            ],
            options={
                'db_table': 'ARTICULO_CONVERSION',
            },
        ),
    ]
