"""
Django settings for prefacturas project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from importlib.util import find_spec
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def _normalize_sqlserver_extra_params(raw_value):
    parts = []
    for chunk in str(raw_value or "").split(";"):
        item = chunk.strip()
        if not item:
            continue
        key = item.split("=", 1)[0].strip().lower()
        # django-mssql-backend ya agrega MARS_Connection=yes en Windows.
        if key == "mars_connection":
          continue
        parts.append(item)
    return ";".join(parts)


def _env_value(name, default=""):
    value = os.getenv(name)
    if value is None:
        return default
    text = str(value).strip()
    return text if text else default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-key-change-this",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'prefacturas_app',
    'core',
    'prefacturas_mod',
    'clientes_mod',
    'inventario',
    'reportes',
    'etiquetas',
    'ajustes',
    'cobros',
    'cartas',
    'factura',
    'caja',
    'chat_interno',
    'empleados',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.ServerLocalTimezoneMiddleware',
    'core.middleware.ServerConnectionExperienceMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if find_spec("whitenoise") is not None:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'prefacturas.urls'
ASGI_APPLICATION = 'prefacturas.asgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.server_clock',
            ],
        },
    },
]

WSGI_APPLICATION = 'prefacturas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": _env_value("SQLSERVER_DB", ""),
        "USER": _env_value("SQLSERVER_USER", ""),
        "PASSWORD": _env_value("SQLSERVER_PASSWORD", ""),
        "HOST": _env_value("SQLSERVER_HOST", "localhost"),
        "PORT": _env_value("SQLSERVER_PORT", ""),
        "OPTIONS": {
            "driver": _env_value("SQLSERVER_DRIVER", "ODBC Driver 18 for SQL Server"),
            "extra_params": _normalize_sqlserver_extra_params(
                _env_value("SQLSERVER_EXTRA_PARAMS", "TrustServerCertificate=yes;")
            ),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-bo"

TIME_ZONE = "America/La_Paz"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_USE_FINDERS = DEBUG
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

WHATSAPP_API_VERSION = _env_value("WHATSAPP_API_VERSION", "v23.0")
WHATSAPP_ACCESS_TOKEN = _env_value("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = _env_value("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_WABA_ID = _env_value("WHATSAPP_WABA_ID", "")
WHATSAPP_VERIFY_TOKEN = _env_value("WHATSAPP_VERIFY_TOKEN", "")

QZ_SIGNING_DIR = Path(_env_value("QZ_SIGNING_DIR", str(BASE_DIR / "private" / "qz")))
QZ_CERTIFICATE_PATH = Path(_env_value("QZ_CERTIFICATE_PATH", str(QZ_SIGNING_DIR / "digital-certificate.txt")))
QZ_PRIVATE_KEY_PATH = Path(_env_value("QZ_PRIVATE_KEY_PATH", str(QZ_SIGNING_DIR / "private-key.pem")))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use signed cookie sessions so we don't require the django_session table
# in an existing SQL Server database.
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use signed cookie sessions so we don't require the django_session table
# in an existing SQL Server database.
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

# Keep the custom auth cookie persistent per terminal/device so the app can be
# saved to the home screen and reopened without forcing a new login on browser close.
AUTH_COOKIE_MAX_AGE = int(
    os.getenv("AUTH_COOKIE_MAX_AGE", str(60 * 60 * 24 * 365 * 5))
)
SESSION_COOKIE_AGE = AUTH_COOKIE_MAX_AGE
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

DEVELOPER_USER = _env_value("DEVELOPER_USER", "fgomera")
