# Generated by Django 5.2.12 on 2026-06-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_empleadovacacionbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadoaccionpersonal',
            name='cambio_cargo_anterior',
            field=models.CharField(blank=True, db_column='CAMBIO_CARGO_ANTERIOR', max_length=80),
        ),
        migrations.AddField(
            model_name='empleadoaccionpersonal',
            name='cambio_departamento_anterior',
            field=models.CharField(blank=True, db_column='CAMBIO_DEPARTAMENTO_ANTERIOR', max_length=100),
        ),
        migrations.AddField(
            model_name='empleadoaccionpersonal',
            name='cambio_nomina_anterior',
            field=models.CharField(blank=True, db_column='CAMBIO_NOMINA_ANTERIOR', max_length=80),
        ),
    ]
