# Generated by Django 5.2.12 on 2026-06-03 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0011_empleado_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoVacacionPlanificada',
            fields=[
                ('id_plan', models.AutoField(db_column='ID_PLAN', primary_key=True, serialize=False)),
                ('fecha_desde', models.DateField(db_column='FECHA_DESDE')),
                ('fecha_hasta', models.DateField(db_column='FECHA_HASTA')),
                ('cantidad_dias', models.PositiveSmallIntegerField(db_column='CANTIDAD_DIAS', default=0)),
                ('nota', models.CharField(blank=True, db_column='NOTA', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='CREADO_EN')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='ACTUALIZADO_EN')),
                ('empleado', models.ForeignKey(db_column='ID_EMPLEADO', on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones_planificadas', to='empleados.empleadonomina')),
            ],
            options={
                'db_table': 'EMPLEADO_VACACION_PLANIFICADA',
                'ordering': ['fecha_desde', 'id_plan'],
            },
        ),
    ]
