# Generated by Django 5.2.12 on 2026-06-03 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0012_empleadovacacionplanificada'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaPeriodo',
            fields=[
                ('id_periodo', models.AutoField(db_column='ID_PERIODO', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='TIPO', max_length=20)),
                ('fecha_desde', models.DateField(db_column='FECHA_DESDE')),
                ('fecha_hasta', models.DateField(db_column='FECHA_HASTA')),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=120)),
                ('estatus', models.CharField(db_column='ESTATUS', default='BORRADOR', max_length=20)),
                ('aplicar_afp', models.BooleanField(db_column='APLICAR_AFP', default=False)),
                ('aplicar_sfs', models.BooleanField(db_column='APLICAR_SFS', default=False)),
                ('aplicar_srl', models.BooleanField(db_column='APLICAR_SRL', default=False)),
                ('aplicar_isr', models.BooleanField(db_column='APLICAR_ISR', default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='CREADO_EN')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='ACTUALIZADO_EN')),
            ],
            options={
                'db_table': 'NOMINA_PERIODO',
                'ordering': ['-fecha_desde', '-id_periodo'],
            },
        ),
        migrations.CreateModel(
            name='NominaAdelanto',
            fields=[
                ('id_adelanto', models.AutoField(db_column='ID_ADELANTO', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(db_column='MONTO', decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(db_column='FECHA')),
                ('descontado', models.BooleanField(db_column='DESCONTADO', default=False)),
                ('nota', models.CharField(blank=True, db_column='NOTA', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='CREADO_EN')),
                ('empleado', models.ForeignKey(db_column='ID_EMPLEADO', on_delete=django.db.models.deletion.CASCADE, related_name='adelantos', to='empleados.empleadonomina')),
                ('periodo_descuento', models.ForeignKey(blank=True, db_column='ID_PERIODO_DESCUENTO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adelantos_descontados', to='empleados.nominaperiodo')),
            ],
            options={
                'db_table': 'NOMINA_ADELANTO',
                'ordering': ['-fecha', '-id_adelanto'],
            },
        ),
        migrations.CreateModel(
            name='NominaEntrada',
            fields=[
                ('id_entrada', models.AutoField(db_column='ID_ENTRADA', primary_key=True, serialize=False)),
                ('salario_periodo', models.DecimalField(db_column='SALARIO_PERIODO', decimal_places=2, default=0, max_digits=12)),
                ('dias_trabajados', models.DecimalField(db_column='DIAS_TRABAJADOS', decimal_places=2, default=0, max_digits=6)),
                ('horas_extras_35', models.DecimalField(db_column='HORAS_EXTRAS_35', decimal_places=2, default=0, max_digits=6)),
                ('monto_horas_extras_35', models.DecimalField(db_column='MONTO_HORAS_EXTRAS_35', decimal_places=2, default=0, max_digits=12)),
                ('horas_extras_100', models.DecimalField(db_column='HORAS_EXTRAS_100', decimal_places=2, default=0, max_digits=6)),
                ('monto_horas_extras_100', models.DecimalField(db_column='MONTO_HORAS_EXTRAS_100', decimal_places=2, default=0, max_digits=12)),
                ('bonificacion', models.DecimalField(db_column='BONIFICACION', decimal_places=2, default=0, max_digits=12)),
                ('bonificacion_desc', models.CharField(blank=True, db_column='BONIFICACION_DESC', max_length=120)),
                ('comisiones', models.DecimalField(db_column='COMISIONES', decimal_places=2, default=0, max_digits=12)),
                ('vacaciones_pagadas', models.DecimalField(db_column='VACACIONES_PAGADAS', decimal_places=2, default=0, max_digits=12)),
                ('regalia', models.DecimalField(db_column='REGALIA', decimal_places=2, default=0, max_digits=12)),
                ('otros_ingresos', models.DecimalField(db_column='OTROS_INGRESOS', decimal_places=2, default=0, max_digits=12)),
                ('otros_ingresos_desc', models.CharField(blank=True, db_column='OTROS_INGRESOS_DESC', max_length=120)),
                ('afp_empleado', models.DecimalField(db_column='AFP_EMPLEADO', decimal_places=2, default=0, max_digits=12)),
                ('afp_empleador', models.DecimalField(db_column='AFP_EMPLEADOR', decimal_places=2, default=0, max_digits=12)),
                ('sfs_empleado', models.DecimalField(db_column='SFS_EMPLEADO', decimal_places=2, default=0, max_digits=12)),
                ('sfs_empleador', models.DecimalField(db_column='SFS_EMPLEADOR', decimal_places=2, default=0, max_digits=12)),
                ('srl_empleador', models.DecimalField(db_column='SRL_EMPLEADOR', decimal_places=2, default=0, max_digits=12)),
                ('isr_retencion', models.DecimalField(db_column='ISR_RETENCION', decimal_places=2, default=0, max_digits=12)),
                ('adelanto', models.DecimalField(db_column='ADELANTO', decimal_places=2, default=0, max_digits=12)),
                ('prestamo_descuento', models.DecimalField(db_column='PRESTAMO_DESCUENTO', decimal_places=2, default=0, max_digits=12)),
                ('otras_deducciones', models.DecimalField(db_column='OTRAS_DEDUCCIONES', decimal_places=2, default=0, max_digits=12)),
                ('otras_deducciones_desc', models.CharField(blank=True, db_column='OTRAS_DEDUCCIONES_DESC', max_length=120)),
                ('total_ingresos', models.DecimalField(db_column='TOTAL_INGRESOS', decimal_places=2, default=0, max_digits=12)),
                ('total_deducciones_legales', models.DecimalField(db_column='TOTAL_DEDUCCIONES_LEGALES', decimal_places=2, default=0, max_digits=12)),
                ('total_otras_deducciones', models.DecimalField(db_column='TOTAL_OTRAS_DEDUCCIONES', decimal_places=2, default=0, max_digits=12)),
                ('neto_pagar', models.DecimalField(db_column='NETO_PAGAR', decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True, db_column='NOTAS')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='CREADO_EN')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='ACTUALIZADO_EN')),
                ('empleado', models.ForeignKey(db_column='ID_EMPLEADO', on_delete=django.db.models.deletion.PROTECT, related_name='nomina_entradas', to='empleados.empleadonomina')),
                ('periodo', models.ForeignKey(db_column='ID_PERIODO', on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='empleados.nominaperiodo')),
            ],
            options={
                'db_table': 'NOMINA_ENTRADA',
                'ordering': ['empleado__codigo'],
                'constraints': [models.UniqueConstraint(fields=('periodo', 'empleado'), name='uq_nomina_entrada_periodo_empleado')],
            },
        ),
    ]
