# Generated by Django 5.2.12 on 2026-06-03 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0013_nomina_periodo_entrada_adelanto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoVacacionDescuento',
            fields=[
                ('id_descuento', models.AutoField(db_column='ID_DESCUENTO', primary_key=True, serialize=False)),
                ('dias', models.PositiveSmallIntegerField(db_column='DIAS')),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=200)),
                ('fecha_descuento', models.DateField(db_column='FECHA_DESCUENTO')),
                ('fecha_dias_desde', models.DateField(db_column='FECHA_DIAS_DESDE')),
                ('fecha_dias_hasta', models.DateField(db_column='FECHA_DIAS_HASTA')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='CREADO_EN')),
                ('empleado', models.ForeignKey(db_column='ID_EMPLEADO', on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_vacaciones', to='empleados.empleadonomina')),
            ],
            options={
                'db_table': 'EMPLEADO_VACACION_DESCUENTO',
                'ordering': ['-fecha_descuento', '-id_descuento'],
            },
        ),
    ]
