from django.urls import path

from .views import (
    actualizar_cliente_view,
    buscar_clientes_view,
    buscar_prefacturas_view,
    buscar_articulos_view,
    buscar_grupos_articulos_view,
    detalle_grupo_articulos_view,
    detalle_grupo_articulos_prefactura_view,
    guardar_grupo_articulos_view,
    actualizar_prefactura_view,
    crear_prefactura_view,
    actualizar_estado_prefactura_view,
    buscar_proyectos_view,
    buscar_cebes_view,
    buscar_unidad_medida_view,
    detalle_prefactura_view,
    guardar_comentario_linea_prefactura_view,
    buscar_condicion_pago_view,
    buscar_lista_precio_view,
    crear_cliente_view,
    detalle_cliente_view,
    estado_cuenta_print_view,
    buscar_stock_articulos_view,
    stock_articulos_print_view,
    buscar_grupo_cliente_view,
    buscar_vend_comp_view,
    cambiar_password_view,
    guardar_formato_etiquetas_view,
    inicio_view,
    login_view,
    obtener_formato_etiquetas_view,
    logout_view,
    subir_foto_cliente_view,
)

urlpatterns = [
    path("", login_view, name="login"),
    path("inicio/", inicio_view, name="inicio"),
    path("estado-cuenta/impresion/", estado_cuenta_print_view, name="estado_cuenta_impresion"),
    path("articulos/stock/buscar/", buscar_stock_articulos_view, name="buscar_stock_articulos"),
    path("articulos/stock/impresion/", stock_articulos_print_view, name="stock_articulos_impresion"),
    path("clientes/buscar/", buscar_clientes_view, name="buscar_clientes"),
    path("prefacturas/buscar/", buscar_prefacturas_view, name="buscar_prefacturas"),
    path("articulos/buscar/", buscar_articulos_view, name="buscar_articulos"),
    path("grupos-articulos/buscar/", buscar_grupos_articulos_view, name="buscar_grupos_articulos"),
    path("grupos-articulos/detalle/", detalle_grupo_articulos_view, name="detalle_grupo_articulos"),
    path("grupos-articulos/detalle-prefactura/", detalle_grupo_articulos_prefactura_view, name="detalle_grupo_articulos_prefactura"),
    path("grupos-articulos/guardar/", guardar_grupo_articulos_view, name="guardar_grupo_articulos"),
    path("prefacturas/actualizar/", actualizar_prefactura_view, name="actualizar_prefactura"),
    path("prefacturas/crear/", crear_prefactura_view, name="crear_prefactura"),
    path("prefacturas/estado/actualizar/", actualizar_estado_prefactura_view, name="actualizar_estado_prefactura"),
    path("prefacturas/detalle/", detalle_prefactura_view, name="detalle_prefactura"),
    path("prefacturas/detalle/comentario-linea/guardar/", guardar_comentario_linea_prefactura_view, name="guardar_comentario_linea_prefactura"),
    path("unidad-medida/buscar/", buscar_unidad_medida_view, name="buscar_unidad_medida"),
    path("proyectos/buscar/", buscar_proyectos_view, name="buscar_proyectos"),
    path("cebes/buscar/", buscar_cebes_view, name="buscar_cebes"),
    path("clientes/detalle/", detalle_cliente_view, name="detalle_cliente"),
    path("clientes/crear/", crear_cliente_view, name="crear_cliente"),
    path("clientes/actualizar/", actualizar_cliente_view, name="actualizar_cliente"),
    path("clientes/foto/subir/", subir_foto_cliente_view, name="subir_foto_cliente"),
    path("grupos-cliente/buscar/", buscar_grupo_cliente_view, name="buscar_grupo_cliente"),
    path("vend-comp/buscar/", buscar_vend_comp_view, name="buscar_vend_comp"),
    path("condiciones-pago/buscar/", buscar_condicion_pago_view, name="buscar_condicion_pago"),
    path("lista-precio/buscar/", buscar_lista_precio_view, name="buscar_lista_precio"),
    path("etiquetas/formato/obtener/", obtener_formato_etiquetas_view, name="obtener_formato_etiquetas"),
    path("etiquetas/formato/guardar/", guardar_formato_etiquetas_view, name="guardar_formato_etiquetas"),
    path("auth/cambiar-password/", cambiar_password_view, name="cambiar_password"),
    path("logout/", logout_view, name="logout"),
]
