from django.urls import path

from .views import (
    catalogo_cuentas_detalle_view,
    catalogo_cuentas_financ_view,
    financiamiento_buscar_view,
    financiamiento_guardar_view,
    financiamiento_detalle_view,
    financiamiento_facturas_disponibles_view,
    cuentas_por_cobrar_buscar_view,
    cuentas_por_cobrar_cancelar_view,
    cuentas_por_cobrar_cobros_anteriores_view,
    cuentas_por_cobrar_historial_pago_view,
    cuentas_por_cobrar_corregir_monto_view,
    cuentas_por_cobrar_detalle_view,
    cuentas_por_cobrar_guardar_view,
    cuentas_por_cobrar_marcar_impreso_view,
    cuentas_por_cobrar_medio_pago_view,
    cuentas_por_cobrar_pdf_view,
    cuentas_por_cobrar_print_data_view,
    cuentas_por_cobrar_pendientes_view,
    cuentas_por_cobrar_view,
    cuadre_caja_view,
    financiamiento_view,
    index,
    caja_pos_view,
    caja_pos_session_status_view,
    caja_pos_session_open_view,
    caja_pos_session_close_view,
    caja_pos_buscar_articulo_view,
    caja_pos_buscar_cliente_view,
    caja_pos_save_sale_view,
    caja_pos_ticket_print_data_view,
    caja_pos_session_print_close_view,
    caja_pos_sales_list_view,
    caja_pos_sales_detail_view,
    caja_pos_sales_cancel_view,
)

app_name = "caja"

urlpatterns = [
    path("", index, name="index"),
    path("cuentas-por-cobrar/", cuentas_por_cobrar_view, name="cuentas_por_cobrar"),
    path(
        "cuentas-por-cobrar/pendientes/",
        cuentas_por_cobrar_pendientes_view,
        name="cuentas_por_cobrar_pendientes",
    ),
    path(
        "cuentas-por-cobrar/buscar/",
        cuentas_por_cobrar_buscar_view,
        name="cuentas_por_cobrar_buscar",
    ),
    path(
        "cuentas-por-cobrar/detalle/",
        cuentas_por_cobrar_detalle_view,
        name="cuentas_por_cobrar_detalle",
    ),
    path(
        "cuentas-por-cobrar/cobros-anteriores/",
        cuentas_por_cobrar_cobros_anteriores_view,
        name="cuentas_por_cobrar_cobros_anteriores",
    ),
    path(
        "cuentas-por-cobrar/historial-pago/",
        cuentas_por_cobrar_historial_pago_view,
        name="cuentas_por_cobrar_historial_pago",
    ),
    path(
        "cuentas-por-cobrar/print-data/",
        cuentas_por_cobrar_print_data_view,
        name="cuentas_por_cobrar_print_data",
    ),
    path(
        "cuentas-por-cobrar/pdf/",
        cuentas_por_cobrar_pdf_view,
        name="cuentas_por_cobrar_pdf",
    ),
    path(
        "cuentas-por-cobrar/guardar/",
        cuentas_por_cobrar_guardar_view,
        name="cuentas_por_cobrar_guardar",
    ),
    path(
        "cuentas-por-cobrar/marcar-impreso/",
        cuentas_por_cobrar_marcar_impreso_view,
        name="cuentas_por_cobrar_marcar_impreso",
    ),
    path(
        "cuentas-por-cobrar/medio-pago/",
        cuentas_por_cobrar_medio_pago_view,
        name="cuentas_por_cobrar_medio_pago",
    ),
    path(
        "cuentas-por-cobrar/corregir-monto/",
        cuentas_por_cobrar_corregir_monto_view,
        name="cuentas_por_cobrar_corregir_monto",
    ),
    path(
        "cuentas-por-cobrar/cancelar/",
        cuentas_por_cobrar_cancelar_view,
        name="cuentas_por_cobrar_cancelar",
    ),
    path(
        "catalogo/cuentas-detalle/",
        catalogo_cuentas_detalle_view,
        name="catalogo_cuentas_detalle",
    ),
    path(
        "catalogo/cuentas-financ/",
        catalogo_cuentas_financ_view,
        name="catalogo_cuentas_financ",
    ),
    path("cuadre-caja/", cuadre_caja_view, name="cuadre_caja"),
    path("financiamiento/", financiamiento_view, name="financiamiento"),
    path("financiamiento/buscar/", financiamiento_buscar_view, name="financiamiento_buscar"),
    path(
        "financiamiento/facturas-disponibles/",
        financiamiento_facturas_disponibles_view,
        name="financiamiento_facturas_disponibles",
    ),
    path("financiamiento/detalle/", financiamiento_detalle_view, name="financiamiento_detalle"),
    path("financiamiento/guardar/", financiamiento_guardar_view, name="financiamiento_guardar"),
    # POS routes
    path("pos/", caja_pos_view, name="pos"),
    path("pos/articulo/buscar/", caja_pos_buscar_articulo_view, name="pos_buscar_articulo"),
    path("pos/session/status/", caja_pos_session_status_view, name="pos_session_status"),
    path("pos/session/open/", caja_pos_session_open_view, name="pos_session_open"),
    path("pos/session/close/", caja_pos_session_close_view, name="pos_session_close"),
    path("pos/save-sale/", caja_pos_save_sale_view, name="pos_save_sale"),
    path("pos/cliente/buscar/", caja_pos_buscar_cliente_view, name="pos_buscar_cliente"),
    path("pos/ticket/print-data/", caja_pos_ticket_print_data_view, name="pos_ticket_print_data"),
    path("pos/session/print-close/", caja_pos_session_print_close_view, name="pos_session_print_close"),
    path("pos/sales/list/", caja_pos_sales_list_view, name="pos_sales_list"),
    path("pos/sales/detail/", caja_pos_sales_detail_view, name="pos_sales_detail"),
    path("pos/sales/cancel/", caja_pos_sales_cancel_view, name="pos_sales_cancel"),
]
