# Generated by Django 5.2.12 on 2026-06-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0013_feriadonacional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impresoraconfig',
            options={'ordering': ['tipo_documento']},
        ),
        migrations.RemoveConstraint(
            model_name='impresoraconfig',
            name='uq_impresora_terminal_tipo',
        ),
        migrations.RemoveField(
            model_name='impresoraconfig',
            name='nombre_terminal',
        ),
        migrations.AlterField(
            model_name='impresoraconfig',
            name='tipo_documento',
            field=models.CharField(choices=[('cxc', 'Cuentas por Cobrar'), ('factura', 'Factura'), ('financiamiento', 'Financiamiento')], db_column='TIPO_DOCUMENTO', max_length=40, unique=True),
        ),
    ]
