# Generated by Django 5.2.12 on 2026-06-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0014_alter_impresoraconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresoraconfig',
            name='tipo_documento',
            field=models.CharField(choices=[('cxc', 'Cuentas por Cobrar'), ('factura', 'Factura'), ('financiamiento', 'Financiamiento'), ('ticket', 'Venta POS')], db_column='TIPO_DOCUMENTO', max_length=40, unique=True),
        ),
    ]
