from django.urls import path

from .views import (
    aprobar_ecf_view,
    cancelar_factura_view,
    facturacion_cancelar_factura_view,
    facturacion_articulos_buscar_view,
    facturacion_cebes_buscar_view,
    facturacion_factura_detalle_view,
    facturacion_cliente_detalle_view,
    facturacion_clientes_buscar_view,
    facturacion_proyectos_buscar_view,
    facturacion_unidad_medida_buscar_view,
    emitir_factura_manual_view,
    emitir_factura_view,
    facturacion_view,
    facturas_buscar_view,
    emision_prefactura_detalle_view,
    emision_prefactura_lock_view,
    emision_prefacturas_view,
    emision_prefacturas_status_view,
    electronica_view,
    factura_print_view,
    index,
    emision_view,
    recibir_ecf_view,
)

app_name = "factura"

urlpatterns = [
    path("", index, name="index"),
    path("facturacion/", facturacion_view, name="facturacion"),
    path("facturacion/emitir/", emitir_factura_manual_view, name="emitir_factura_manual"),
    path("facturacion/facturas/cancelar/", facturacion_cancelar_factura_view, name="facturacion_cancelar_factura"),
    path("facturacion/clientes/buscar/", facturacion_clientes_buscar_view, name="facturacion_clientes_buscar"),
    path("facturacion/clientes/detalle/", facturacion_cliente_detalle_view, name="facturacion_cliente_detalle"),
    path("facturacion/facturas/detalle/", facturacion_factura_detalle_view, name="facturacion_factura_detalle"),
    path("facturacion/articulos/buscar/", facturacion_articulos_buscar_view, name="facturacion_articulos_buscar"),
    path("facturacion/unidad-medida/buscar/", facturacion_unidad_medida_buscar_view, name="facturacion_unidad_medida_buscar"),
    path("facturacion/proyectos/buscar/", facturacion_proyectos_buscar_view, name="facturacion_proyectos_buscar"),
    path("facturacion/cebes/buscar/", facturacion_cebes_buscar_view, name="facturacion_cebes_buscar"),
    path("emision/", emision_view, name="emision"),
    path("emision/prefacturas/", emision_prefacturas_view, name="emision_prefacturas"),
    path("emision/prefacturas/status/", emision_prefacturas_status_view, name="emision_prefacturas_status"),
    path("emision/prefacturas/lock/", emision_prefactura_lock_view, name="emision_prefactura_lock"),
    path("emision/prefactura-detalle/", emision_prefactura_detalle_view, name="emision_prefactura_detalle"),
    path("emision/facturas/", facturas_buscar_view, name="buscar_facturas"),
    path("emision/facturas/cancelar/", cancelar_factura_view, name="cancelar_factura"),
    path("emision/emitir/", emitir_factura_view, name="emitir_factura"),
    path("impresion/", factura_print_view, name="factura_impresion"),
    path("electronica/", electronica_view, name="electronica"),
    path("ecf/recepcion/", recibir_ecf_view, name="ecf_recepcion"),
    path("ecf/aprobacion/", aprobar_ecf_view, name="ecf_aprobacion"),
]
