# Generated by Django 5.2.12 on 2026-04-09 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSala',
            fields=[
                ('id_sala', models.AutoField(db_column='ID_SALA', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='TIPO', default='DIRECTO', max_length=10)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=120, null=True)),
                ('direct_key', models.CharField(blank=True, db_column='DIRECT_KEY', max_length=80, null=True, unique=True)),
                ('creada_por', models.BigIntegerField(blank=True, db_column='CREADA_POR', null=True)),
                ('activa', models.BooleanField(db_column='ACTIVA', default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True, db_column='CREADA_EN')),
                ('actualizada_en', models.DateTimeField(auto_now=True, db_column='ACTUALIZADA_EN')),
            ],
            options={
                'db_table': 'CHAT_SALA',
                'ordering': ['-actualizada_en', '-id_sala'],
            },
        ),
        migrations.CreateModel(
            name='ChatMensaje',
            fields=[
                ('id_mensaje', models.AutoField(db_column='ID_MENSAJE', primary_key=True, serialize=False)),
                ('id_usuario', models.BigIntegerField(db_column='ID_USUARIO')),
                ('usuario_nombre', models.CharField(blank=True, db_column='USUARIO_NOMBRE', max_length=120, null=True)),
                ('contenido', models.TextField(db_column='CONTENIDO')),
                ('event_id', models.CharField(blank=True, db_column='EVENT_ID', max_length=80, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='CREADO_EN')),
                ('sala', models.ForeignKey(db_column='ID_SALA', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat_interno.chatsala')),
            ],
            options={
                'db_table': 'CHAT_MENSAJE',
                'ordering': ['id_mensaje'],
            },
        ),
        migrations.CreateModel(
            name='ChatSalaMiembro',
            fields=[
                ('id_miembro', models.AutoField(db_column='ID_MIEMBRO', primary_key=True, serialize=False)),
                ('id_usuario', models.BigIntegerField(db_column='ID_USUARIO')),
                ('usuario_nombre', models.CharField(blank=True, db_column='USUARIO_NOMBRE', max_length=120, null=True)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('unido_en', models.DateTimeField(auto_now_add=True, db_column='UNIDO_EN')),
                ('sala', models.ForeignKey(db_column='ID_SALA', on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='chat_interno.chatsala')),
            ],
            options={
                'db_table': 'CHAT_SALA_MIEMBRO',
                'constraints': [models.UniqueConstraint(fields=('sala', 'id_usuario'), name='uq_chat_sala_usuario')],
            },
        ),
    ]
