# Generated by Django 5.2.12 on 2026-04-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_interno", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMensajeLectura",
            fields=[
                ("id_lectura", models.AutoField(db_column="ID_LECTURA", primary_key=True, serialize=False)),
                ("id_usuario", models.BigIntegerField(db_column="ID_USUARIO")),
                ("leido_en", models.DateTimeField(auto_now_add=True, db_column="LEIDO_EN")),
                (
                    "mensaje",
                    models.ForeignKey(
                        db_column="ID_MENSAJE",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturas",
                        to="chat_interno.chatmensaje",
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        db_column="ID_SALA",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturas",
                        to="chat_interno.chatsala",
                    ),
                ),
            ],
            options={
                "db_table": "CHAT_MENSAJE_LECTURA",
            },
        ),
        migrations.AddConstraint(
            model_name="chatmensajelectura",
            constraint=models.UniqueConstraint(fields=("mensaje", "id_usuario"), name="uq_chat_msg_user_read"),
        ),
    ]
