from django.urls import path

from .views import (
    articulos_view,
    entrada_articulos_articulos_view,
    entrada_articulos_buscar_view,
    entrada_articulos_detalle_view,
    entrada_articulos_guardar_view,
    entrada_articulos_proveedores_view,
    entrada_articulos_view,
    grupos_view,
    index,
    notification_state_delivered_view,
    notification_state_hide_view,
    notification_state_mark_read_bulk_view,
    notification_state_mark_read_view,
    salida_articulos_articulos_view,
    salida_articulos_buscar_view,
    salida_articulos_detalle_view,
    salida_articulos_guardar_view,
    salida_articulos_proveedores_view,
    salida_articulos_view,
    solicitudes_existencia_crear_view,
    solicitudes_existencia_detalle_view,
    solicitudes_existencia_eliminar_view,
    solicitudes_existencia_lista_view,
    solicitudes_existencia_operativas_view,
    solicitudes_existencia_marcar_leida_view,
    solicitudes_existencia_resumen_view,
    stock_view,
    articulos_list_view,
    articulo_save_view,
)

app_name = "inventario"

urlpatterns = [
    path("", index, name="index"),
    path("articulos/", articulos_view, name="articulos"),
    path("solicitudes-existencia/", solicitudes_existencia_resumen_view, name="solicitudes_existencia_resumen"),
    path("notificaciones/<str:notification_id>/marcar-leida/", notification_state_mark_read_view, name="notification_state_mark_read"),
    path("notificaciones/marcar-leidas/", notification_state_mark_read_bulk_view, name="notification_state_mark_read_bulk"),
    path("notificaciones/<str:notification_id>/ocultar/", notification_state_hide_view, name="notification_state_hide"),
    path("notificaciones/entregadas/", notification_state_delivered_view, name="notification_state_delivered"),
    path("solicitudes-existencia/lista/", solicitudes_existencia_lista_view, name="solicitudes_existencia_lista"),
    path("solicitudes-existencia/operativas/", solicitudes_existencia_operativas_view, name="solicitudes_existencia_operativas"),
    path("solicitudes-existencia/crear/", solicitudes_existencia_crear_view, name="solicitudes_existencia_crear"),
    path(
        "solicitudes-existencia/<int:solicitud_id>/marcar-leida/",
        solicitudes_existencia_marcar_leida_view,
        name="solicitudes_existencia_marcar_leida",
    ),
    path(
        "solicitudes-existencia/<int:solicitud_id>/eliminar/",
        solicitudes_existencia_eliminar_view,
        name="solicitudes_existencia_eliminar",
    ),
    path(
        "solicitudes-existencia/<int:solicitud_id>/",
        solicitudes_existencia_detalle_view,
        name="solicitudes_existencia_detalle",
    ),
    path("entrada-articulos/", entrada_articulos_view, name="entrada_articulos"),
    path("entrada-articulos/buscar/", entrada_articulos_buscar_view, name="entrada_articulos_buscar"),
    path("entrada-articulos/detalle/", entrada_articulos_detalle_view, name="entrada_articulos_detalle"),
    path("entrada-articulos/proveedores/", entrada_articulos_proveedores_view, name="entrada_articulos_proveedores"),
    path("entrada-articulos/articulos/", entrada_articulos_articulos_view, name="entrada_articulos_articulos"),
    path("entrada-articulos/guardar/", entrada_articulos_guardar_view, name="entrada_articulos_guardar"),
    path("salida-articulos/", salida_articulos_view, name="salida_articulos"),
    path("salida-articulos/buscar/", salida_articulos_buscar_view, name="salida_articulos_buscar"),
    path("salida-articulos/detalle/", salida_articulos_detalle_view, name="salida_articulos_detalle"),
    path("salida-articulos/proveedores/", salida_articulos_proveedores_view, name="salida_articulos_proveedores"),
    path("salida-articulos/articulos/", salida_articulos_articulos_view, name="salida_articulos_articulos"),
    path("salida-articulos/guardar/", salida_articulos_guardar_view, name="salida_articulos_guardar"),
    path("grupos/", grupos_view, name="grupos"),
    path("stock/", stock_view, name="stock"),
    path("articulos/list/", articulos_list_view, name="articulos_list"),
    path("articulos/save/", articulo_save_view, name="articulo_save"),
]
