from django.urls import path

from .views import (
    index,
    usuarios_view,
    parametros_view,
    parametros_empresa_view,
    parametros_feriados_view,
    parametros_sistema_impresion_view,
    parametros_sectores_view,
    integraciones_view,
    facturacion_electronica_view,
    whatsapp_view,
    reportes_transunion_view,
    reportes_transunion_cuentas_view,
    reportes_transunion_generar_view,
    reportes_transunion_actualizar_cuentas_view,
    guardar_parametros_view,
    guardar_formatos_impresion_view,
    guardar_feriado_view,
    preferencias_impresora_view,
    guardar_preferencias_impresora_view,
    guardar_fact_stock_view,
    guardar_codigo_variable_view,
    eliminar_codigo_variable_view,
    crear_sector_view,
    editar_sector_view,
    crear_modulo_view,
    crear_permiso_view,
    crear_rol_view,
    asignar_rol_view,
    asignar_permiso_rol_view,
    asignar_permiso_usuario_view,
    guardar_permisos_usuario_view,
    guardar_firma_usuario_view,
    guardar_usuario_view,
    guardar_preferencia_caja_usuario_view,
    toggle_permiso_activo_view,
)

app_name = "ajustes"

urlpatterns = [
    path("", index, name="index"),
    path("usuarios/", usuarios_view, name="usuarios"),
    path("usuarios/modulos/crear/", crear_modulo_view, name="crear_modulo"),
    path("usuarios/permisos/crear/", crear_permiso_view, name="crear_permiso"),
    path("usuarios/roles/crear/", crear_rol_view, name="crear_rol"),
    path("usuarios/roles/asignar/", asignar_rol_view, name="asignar_rol"),
    path("usuarios/roles/permisos/asignar/", asignar_permiso_rol_view, name="asignar_permiso_rol"),
    path("usuarios/permisos/asignar/", asignar_permiso_usuario_view, name="asignar_permiso_usuario"),
    path("usuarios/permisos/guardar/", guardar_permisos_usuario_view, name="guardar_permisos_usuario"),
    path("usuarios/permisos/toggle-activo/", toggle_permiso_activo_view, name="toggle_permiso_activo"),
    path("usuarios/guardar/", guardar_usuario_view, name="guardar_usuario"),
    path("usuarios/firma/guardar/", guardar_firma_usuario_view, name="guardar_firma_usuario"),
    path("usuarios/caja-preferencia/guardar/", guardar_preferencia_caja_usuario_view, name="guardar_preferencia_caja_usuario"),
    path("parametros/", parametros_view, name="parametros"),
    path("parametros/empresa/", parametros_empresa_view, name="parametros_empresa"),
    path("parametros/feriados/", parametros_feriados_view, name="parametros_feriados"),
    path("parametros/sistema-impresion/", parametros_sistema_impresion_view, name="parametros_sistema_impresion"),
    path("parametros/sectores/", parametros_sectores_view, name="parametros_sectores"),
    path("parametros/guardar/", guardar_parametros_view, name="guardar_parametros"),
    path("parametros/formatos/guardar/", guardar_formatos_impresion_view, name="guardar_formatos_impresion"),
    path("parametros/feriados/guardar/", guardar_feriado_view, name="guardar_feriado"),
    path("parametros/impresoras/preferencias/", preferencias_impresora_view, name="preferencias_impresora"),
    path("parametros/impresoras/guardar/", guardar_preferencias_impresora_view, name="guardar_preferencias_impresora"),
    path("parametros/fact-stock/guardar/", guardar_fact_stock_view, name="guardar_fact_stock"),
    path("parametros/codigo-variable/guardar/", guardar_codigo_variable_view, name="guardar_codigo_variable"),
    path("parametros/codigo-variable/eliminar/", eliminar_codigo_variable_view, name="eliminar_codigo_variable"),
    path("parametros/sectores/crear/", crear_sector_view, name="crear_sector"),
    path("parametros/sectores/editar/", editar_sector_view, name="editar_sector"),
    path("integraciones/", integraciones_view, name="integraciones"),
    path("integraciones/facturacion-electronica/", facturacion_electronica_view, name="facturacion_electronica"),
    path("integraciones/whatsapp/", whatsapp_view, name="whatsapp"),
    path("integraciones/reportes-transunion/", reportes_transunion_view, name="reportes_transunion"),
    path("integraciones/reportes-transunion/cuentas/", reportes_transunion_cuentas_view, name="reportes_transunion_cuentas"),
    path("integraciones/reportes-transunion/generar/", reportes_transunion_generar_view, name="reportes_transunion_generar"),
    path("integraciones/reportes-transunion/actualizar-cuentas/", reportes_transunion_actualizar_cuentas_view, name="reportes_transunion_actualizar_cuentas"),
]
